name: build-linux

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev python3-tk build-essential libasound2-dev libudev-dev libevdev-dev patchelf

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller pyinstaller.spec --noconfirm --clean --distpath dist --workpath build

      - name: Package artifact
        run: |
          tar -czf lexisharp-linux.tar.gz -C dist lexisharp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lexisharp-linux
          path: |
            lexisharp-linux.tar.gz
          if-no-files-found: error
